export const DEFAULT_REGISTRATIONS_PATH = 'app/registrations';
export const DEFAULT_COMPONENT_REGISTRATIONS_FILE_NAME =
  'component-registrations.ts';

export const DEFAULT_SCHEMATICS_CONFIG_PATH = 'app';
export const DEFAULT_SCHEMATIC_CONFIG_FILE_NAME = 'formbar-schematic.config.json';

export const NGX_FW_COMPONENT_REGISTRATIONS = 'NGX_FW_COMPONENT_REGISTRATIONS';
export const NGX_FW_VALIDATOR_REGISTRATIONS = 'NGX_FW_VALIDATOR_REGISTRATIONS';
export const NGX_FW_ASYNC_VALIDATOR_REGISTRATIONS =
  'NGX_FW_ASYNC_VALIDATOR_REGISTRATIONS';

export const DEFAULT_REGISTRATION_TYPE = 'token';
