name: Test and Lint

on:
  pull_request:
    branches:
      - main
      - develop
      - 'release/**'
    paths:
      - 'projects/core'
  workflow_dispatch:
  workflow_call:

jobs:

  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Get and cache dependencies
        uses: ./.github/actions/cached-dependencies

      - name: Lint
        run: npm run lint

      - name: Build (required for schematic tests)
        run: npm run build

      - name: Show contents of schematics folder
        run: |
          echo "=== dist/core ==="
          ls -lR dist/core/schematics
        shell: bash

      - name: Run tests
        run: |
          npm run test:component
          npm run test:node
          npm run cypress:run

