name: Publish
on:
  workflow_dispatch:
  workflow_call:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Download Release Assets
        run: |
          gh release download ${{ github.event.release.tag_name }} \
            --pattern "*.tgz"

      - name: Publish to NPM
        run: npm publish *.tgz --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
