name: Publish to npm

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'GitHub release tag (e.g. @ngx-formbar/core@1.1.0)'
        required: true
        type: string
      dist_tag:
        description: 'npm dist-tag'
        required: true
        type: choice
        options:
          - latest
          - next
        default: 'latest'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Download Release Assets
        run: |
          gh release download "${{ inputs.release_tag }}" \
            --pattern "*.tgz"

      - name: Publish to npm
        run: npm publish *.tgz --provenance --access public --tag ${{ inputs.dist_tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
