name: publish.yml
on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Download Release Assets
        run: |
          gh release download ${{ github.event.release.tag_name }} \
            --pattern "*.tgz"

      - name: Publish to NPM
        run: npm publish *.tgz --provenance --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
